(**
    Generate strings for a waveform diagram generated by a circuit,
    given some inputs

    Inspired by Jane Street's hardcaml_waveterm library:
    https://github.com/janestreet/hardcaml_waveterm

    @param c The circuit to simulate
    @param n The number of ticks to simulate for
    @param inputs The arrray of inputs: inputs.(i).(j) is the jth element
    of the ith input
    @return The waveform diagram as a string
*)
val string_of_waveforms :
    Core.circuit -> int -> Logic.Values.belnap_value array array -> string

(**
    Print a waveform diagram generated by a circuit, given some inputs

    @param c The circuit to simulate
    @param n The number of ticks to simulate for
    @param inputs The arrray of inputs: inputs.(i).(j) is the jth element
    of the ith input
*)
val print_waveforms :
    Core.circuit -> int -> Logic.Values.belnap_value array array -> unit