name: Compile and run example

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v2
      - name: Use OCaml 4.13.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.13.x
      - name: Install opam dependencies
        run: opam install . --deps-only --with-test
      - name: Build and execute the program
        run: opam exec -- dune exec bin/main.exe
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Generate the dot
        run: dot -Tsvg mealy.dot -O
      - name: Upload the build artefact
        uses: actions/upload-artifact@v2
        with:
          name: output.svg
          path: mealy.dot.svg